"""
Convert startup banner design & layout into assembly data.
"""

import json
import sys
from pathlib import Path

DEFAULT_COLOR = 2  # dark blue


def lvllvl2binary(data: dict) -> tuple:
    if data["version"] != 1:
        raise RuntimeError("Unexpected file version")

    layers = data["tileMap"]["layers"]
    if len(layers) != 1:
        raise RuntimeError("Expected exactly one layer, got %s" % len(layers))

    frames = layers[0]["frames"]
    if len(frames) != 1:
        raise RuntimeError("Expected exactly one frame, got %s" % len(frames))

    width = layers[0]["gridWidth"]
    height = layers[0]["gridHeight"]

    frame = frames[0]

    # chars and attribute values
    chars = bytearray()
    attrs = bytearray()

    for data in frame["data"]:
        for cell in data:
            tile = cell["t"]
            fore_color = cell["fc"]
            back_color = cell["bc"]

            if back_color == -1:
                back_color = DEFAULT_COLOR

            if fore_color == -1:
                fore_color = DEFAULT_COLOR

            attr = (fore_color << 4) | back_color

            chars.append(tile)
            attrs.append(attr)

    return (chars, attrs, width, height)


def generate_asm_data(
    *,
    output_path: Path,
    chars: bytearray,
    attrs: bytearray,
    width: int,
    height: int,
    palette: list[str],
    text_placement: dict,
) -> None:
    rle_marker = 255

    with open(output_path, "w", encoding="utf-8") as out:
        out.write(";\n;\tThis file is automatically generated\n;\n")
        out.write(".section boot\n\n")

        out.write("Banner .namespace\n\n")
        out.write(f"RLE_Marker = {rle_marker}\n")
        out.write(f"Height = {height}\n\n")

        for asset, data in {"Attrs": attrs, "Chars": chars}.items():
            out.write(f"{asset}:\n")
            out.write("\t;\tRLE-compressed data:\n")
            out.write("\t;\t\t$FF <byte> <count>\trepeat\n")
            out.write("\t;\t\t$FF 00\t\tend\n")
            rle_data = compress_banner(
                data,
                height=height,
                width=width,
                rle_marker=rle_marker,
            )

            out.write("\t.byte\t{0}\n\n".format(",".join([str(x) for x in rle_data])))  # noqa: UP030

        out.write("Palette:\n")
        for c in palette:
            out.write(f"\t.dword ${c}\n")

        out.write("\n\n; Text placement data\n")
        for category, placement in text_placement.items():
            for k, v in placement.items():
                constant = f"{category}_{k}".title()
                out.write(f"{constant} = {v}\n")

        out.write("\n.endnamespace\n")
        out.write("\n.send boot\n")


def rle_compress(b: list[int], *, marker: int) -> list[int]:
    """Compress a list of bytes using RLE with a specified marker."""
    r: list[int] = []
    while len(b) != 0:
        assert b[0] != marker, f"Compress marker {b[0]} not allowed"

        if len(b) > 3 and b[0] == b[1] and b[1] == b[2]:
            c = 0
            while c < 250 and c + 1 < len(b) and b[0] == b[c + 1]:
                c += 1
            r.append(marker)
            r.append(b[0])
            r.append(c)
            b = b[c:]
        else:
            r.append(b[0])
            b = b[1:]
    r.append(marker)
    r.append(0)
    return r


def compress_banner(
    data: bytearray, *, rle_marker: int, height: int, width: int
) -> list[int]:
    # Convert to list and truncate to banner size
    src = list(data)[: height * width]
    return rle_compress(src, marker=rle_marker)


def load_palette(filepath: Path) -> list[str]:
    with open(filepath, encoding="utf-8") as f:
        return [l for l in [line.strip() for line in f] if l]


def load_json(filepath: Path) -> dict:
    with open(filepath, "rb") as f:
        return json.load(f)


def load_banner(filepath: Path) -> tuple:
    return lvllvl2binary(load_json(filepath))


def main(*, input_dir: Path, build_dir: Path) -> None:
    """Generate assembly data file from lvllvl-authored banner"""

    chars, attrs, width, height = load_banner(input_dir / "banner.json")
    palette = load_palette(input_dir / "palette.hex")
    text_placement = load_json(input_dir / "text_placement.json")

    build_dir.mkdir(parents=True, exist_ok=True)

    generate_asm_data(
        output_path=build_dir / "banner.dat",
        chars=chars,
        attrs=attrs,
        width=width,
        height=height,
        palette=palette,
        text_placement=text_placement,
    )


if __name__ == "__main__":
    main(
        input_dir=Path(sys.argv[1] if len(sys.argv) > 2 else "lvllvl"),
        build_dir=Path(sys.argv[2] if len(sys.argv) > 1 else ".build"),
    )
