[project]
name = "superbasic-docs"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
    "sphinx>=7.0",
    "myst-parser>=2.0",
    "furo>=2024.0",
    "mermaidx>=0.9.4",
    "sphinxcontrib-mermaid>=0.9",
    "sphinx-copybutton>=0.5",
    "sphinx-design>=0.5"
]

[tool.uv]
package = false
