;
;	This is automatically generated.
;
	.section code
KeywordSet0:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	4,$fe,"ABS("           ; $83 ABS(
	.text	6,$93,"ALLOC("         ; $84 ALLOC(
	.text	4,$ff,"ASC("           ; $85 ASC(
	.text	5,$29,"CHR$("          ; $86 CHR$(
	.text	5,$2a,"CWD$("          ; $87 CWD$(
	.text	5,$2b,"DIR$("          ; $88 DIR$(
	.text	4,$07,"DIR("           ; $89 DIR(
	.text	6,$aa,"EVENT("         ; $8a EVENT(
	.text	5,$6b,"FALSE"          ; $8b FALSE
	.text	5,$44,"FRAC("          ; $8c FRAC(
	.text	5,$2c,"GET$("          ; $8d GET$(
	.text	4,$08,"GET("           ; $8e GET(
	.text	9,$4a,"GETDATE$("      ; $8f GETDATE$(
	.text	9,$5b,"GETTIME$("      ; $90 GETTIME$(
	.text	4,$0d,"HIT("           ; $91 HIT(
	.text	7,$cc,"INKEY$("        ; $92 INKEY$(
	.text	6,$a8,"INKEY("         ; $93 INKEY(
	.text	4,$13,"INT("           ; $94 INT(
	.text	6,$a7,"ISVAL("         ; $95 ISVAL(
	.text	10,$e0,"ITEMCOUNT("     ; $96 ITEMCOUNT(
	.text	9,$5b,"ITEMGET$("      ; $97 ITEMGET$(
	.text	5,$5c,"JOYB("          ; $98 JOYB(
	.text	5,$72,"JOYX("          ; $99 JOYX(
	.text	5,$73,"JOYY("          ; $9a JOYY(
	.text	8,$49,"KEYDOWN("       ; $9b KEYDOWN(
	.text	6,$77,"LEFT$("         ; $9c LEFT$(
	.text	4,$07,"LEN("           ; $9d LEN(
	.text	4,$0e,"MAX("           ; $9e MAX(
	.text	5,$26,"MID$("          ; $9f MID$(
	.text	4,$0c,"MIN("           ; $a0 MIN(
	.text	4,$19,"NOT("           ; $a1 NOT(
	.text	5,$4d,"PEEK("          ; $a2 PEEK(
	.text	6,$91,"PEEKD("         ; $a3 PEEKD(
	.text	6,$99,"PEEKL("         ; $a4 PEEKL(
	.text	6,$a4,"PEEKW("         ; $a5 PEEKW(
	.text	8,$3c,"PLAYING("       ; $a6 PLAYING(
	.text	7,$e9,"RANDOM("        ; $a7 RANDOM(
	.text	7,$ca,"RIGHT$("        ; $a8 RIGHT$(
	.text	4,$0c,"RND("           ; $a9 RND(
	.text	8,$0c,"SCREEN$("       ; $aa SCREEN$(
	.text	7,$e8,"SCREEN("        ; $ab SCREEN(
	.text	4,$10,"SGN("           ; $ac SGN(
	.text	4,$0e,"SPC("           ; $ad SPC(
	.text	5,$45,"STR$("          ; $ae STR$(
	.text	5,$56,"TILE("          ; $af TILE(
	.text	6,$a9,"TIMER("         ; $b0 TIMER(
	.text	4,$40,"TRUE"           ; $b1 TRUE
	.text	4,$0b,"VAL("           ; $b2 VAL(
	.text	4,$05,"FRE("           ; $b3 FRE(
	.text	2,$94,"FN"             ; $b4 FN
	.text	3,$e7,"FOR"            ; $b5 FOR
	.text	2,$8f,"IF"             ; $b6 IF
	.text	4,$34,"PROC"           ; $b7 PROC
	.text	6,$c1,"REPEAT"         ; $b8 REPEAT
	.text	5,$79,"WHILE"          ; $b9 WHILE
	.text	5,$6b,"ENDFN"          ; $ba ENDFN
	.text	5,$66,"ENDIF"          ; $bb ENDIF
	.text	7,$0b,"ENDPROC"        ; $bc ENDPROC
	.text	4,$3f,"NEXT"           ; $bd NEXT
	.text	4,$2f,"THEN"           ; $be THEN
	.text	5,$8c,"UNTIL"          ; $bf UNTIL
	.text	4,$2e,"WEND"           ; $c0 WEND
	.text	2,$95,"AT"             ; $c1 AT
	.text	2,$9b,"BY"             ; $c2 BY
	.text	4,$1c,"CALL"           ; $c3 CALL
	.text	6,$b2,"CIRCLE"         ; $c4 CIRCLE
	.text	5,$67,"CLEAR"          ; $c5 CLEAR
	.text	5,$7f,"COLOR"          ; $c6 COLOR
	.text	6,$d4,"COLOUR"         ; $c7 COLOUR
	.text	4,$1a,"DATA"           ; $c8 DATA
	.text	3,$da,"DIM"            ; $c9 DIM
	.text	6,$db,"DOWNTO"         ; $ca DOWNTO
	.text	4,$29,"ELSE"           ; $cb ELSE
	.text	4,$34,"FROM"           ; $cc FROM
	.text	3,$e5,"GFX"            ; $cd GFX
	.text	4,$24,"HERE"           ; $ce HERE
	.text	5,$63,"IMAGE"          ; $cf IMAGE
	.text	3,$e5,"LET"            ; $d0 LET
	.text	4,$28,"LINE"           ; $d1 LINE
	.text	5,$6b,"LOCAL"          ; $d2 LOCAL
	.text	7,$1a,"MEMCOPY"        ; $d3 MEMCOPY
	.text	4,$21,"NAME"           ; $d4 NAME
	.text	3,$db,"OFF"            ; $d5 OFF
	.text	2,$9d,"ON"             ; $d6 ON
	.text	7,$20,"OUTLINE"        ; $d7 OUTLINE
	.text	7,$0f,"PALETTE"        ; $d8 PALETTE
	.text	4,$3f,"PLOT"           ; $d9 PLOT
	.text	4,$2f,"POKE"           ; $da POKE
	.text	5,$73,"POKED"          ; $db POKED
	.text	5,$7b,"POKEL"          ; $dc POKEL
	.text	5,$86,"POKEW"          ; $dd POKEW
	.text	4,$1c,"READ"           ; $de READ
	.text	4,$2e,"RECT"           ; $df RECT
	.text	3,$e4,"REM"            ; $e0 REM
	.text	4,$3b,"SIZE"           ; $e1 SIZE
	.text	5,$7b,"SOLID"          ; $e2 SOLID
	.text	5,$89,"SOUND"          ; $e3 SOUND
	.text	6,$d7,"SPRITE"         ; $e4 SPRITE
	.text	4,$45,"TEXT"           ; $e5 TEXT
	.text	2,$a3,"TO"             ; $e6 TO
	.text	4,$3c,"STEP"           ; $e7 STEP
	.text	$FF
KeywordSet1:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	8,$4c,"ASSEMBLE"       ; $83 ASSEMBLE
	.text	6,$d2,"ASSERT"         ; $84 ASSERT
	.text	6,$bd,"BITMAP"         ; $85 BITMAP
	.text	5,$62,"BLOAD"          ; $86 BLOAD
	.text	5,$71,"BSAVE"          ; $87 BSAVE
	.text	2,$87,"CD"             ; $88 CD
	.text	3,$e2,"CLS"            ; $89 CLS
	.text	6,$d0,"CPRINT"         ; $8a CPRINT
	.text	6,$de,"CURSOR"         ; $8b CURSOR
	.text	3,$df,"DIR"            ; $8c DIR
	.text	5,$7a,"DRIVE"          ; $8d DRIVE
	.text	3,$d7,"END"            ; $8e END
	.text	7,$11,"EXPLODE"        ; $8f EXPLODE
	.text	2,$96,"GO"             ; $90 GO
	.text	5,$80,"GOSUB"          ; $91 GOSUB
	.text	4,$39,"GOTO"           ; $92 GOTO
	.text	5,$90,"INPUT"          ; $93 INPUT
	.text	4,$3c,"LIST"           ; $94 LIST
	.text	4,$20,"LOAD"           ; $95 LOAD
	.text	5,$7a,"LOMEM"          ; $96 LOMEM
	.text	6,$b7,"MDELTA"         ; $97 MDELTA
	.text	5,$89,"MOUSE"          ; $98 MOUSE
	.text	3,$ea,"NEW"            ; $99 NEW
	.text	6,$d9,"OPTION"         ; $9a OPTION
	.text	4,$2e,"PING"           ; $9b PING
	.text	5,$8d,"PRINT"          ; $9c PRINT
	.text	7,$24,"RESTORE"        ; $9d RESTORE
	.text	6,$e0,"RETURN"         ; $9e RETURN
	.text	3,$f5,"RUN"            ; $9f RUN
	.text	4,$2f,"SAVE"           ; $a0 SAVE
	.text	7,$0a,"SETDATE"        ; $a1 SETDATE
	.text	7,$1b,"SETTIME"        ; $a2 SETTIME
	.text	5,$8d,"SHOOT"          ; $a3 SHOOT
	.text	7,$2a,"SPRITES"        ; $a4 SPRITES
	.text	4,$46,"STOP"           ; $a5 STOP
	.text	4,$2e,"TILE"           ; $a6 TILE
	.text	5,$81,"TILES"          ; $a7 TILES
	.text	3,$ff,"TRY"            ; $a8 TRY
	.text	6,$d5,"VERIFY"         ; $a9 VERIFY
	.text	3,$ee,"XGO"            ; $aa XGO
	.text	5,$78,"XLOAD"          ; $ab XLOAD
	.text	3,$eb,"ZAP"            ; $ac ZAP
	.text	$FF
KeywordSet2:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	3,$c8,"ADC"            ; $83 ADC
	.text	3,$d3,"AND"            ; $84 AND
	.text	3,$e0,"ASL"            ; $85 ASL
	.text	3,$c8,"BCC"            ; $86 BCC
	.text	3,$d8,"BCS"            ; $87 BCS
	.text	3,$d8,"BEQ"            ; $88 BEQ
	.text	3,$df,"BIT"            ; $89 BIT
	.text	3,$d8,"BMI"            ; $8a BMI
	.text	3,$d5,"BNE"            ; $8b BNE
	.text	3,$de,"BPL"            ; $8c BPL
	.text	3,$d5,"BRA"            ; $8d BRA
	.text	3,$df,"BRK"            ; $8e BRK
	.text	3,$db,"BVC"            ; $8f BVC
	.text	3,$eb,"BVS"            ; $90 BVS
	.text	3,$d2,"CLC"            ; $91 CLC
	.text	3,$d3,"CLD"            ; $92 CLD
	.text	3,$d8,"CLI"            ; $93 CLI
	.text	3,$e5,"CLV"            ; $94 CLV
	.text	3,$e0,"CMP"            ; $95 CMP
	.text	3,$eb,"CPX"            ; $96 CPX
	.text	3,$ec,"CPY"            ; $97 CPY
	.text	3,$cc,"DEC"            ; $98 DEC
	.text	3,$e1,"DEX"            ; $99 DEX
	.text	3,$e2,"DEY"            ; $9a DEY
	.text	3,$e6,"EOR"            ; $9b EOR
	.text	3,$da,"INC"            ; $9c INC
	.text	3,$ef,"INX"            ; $9d INX
	.text	3,$f0,"INY"            ; $9e INY
	.text	3,$e7,"JMP"            ; $9f JMP
	.text	3,$ef,"JSR"            ; $a0 JSR
	.text	3,$d1,"LDA"            ; $a1 LDA
	.text	3,$e8,"LDX"            ; $a2 LDX
	.text	3,$e9,"LDY"            ; $a3 LDY
	.text	3,$f1,"LSR"            ; $a4 LSR
	.text	3,$ed,"NOP"            ; $a5 NOP
	.text	3,$e2,"ORA"            ; $a6 ORA
	.text	3,$d9,"PHA"            ; $a7 PHA
	.text	3,$e8,"PHP"            ; $a8 PHP
	.text	3,$f0,"PHX"            ; $a9 PHX
	.text	3,$f1,"PHY"            ; $aa PHY
	.text	3,$dd,"PLA"            ; $ab PLA
	.text	3,$ec,"PLP"            ; $ac PLP
	.text	3,$f4,"PLX"            ; $ad PLX
	.text	3,$f5,"PLY"            ; $ae PLY
	.text	3,$ed,"ROL"            ; $af ROL
	.text	3,$f3,"ROR"            ; $b0 ROR
	.text	3,$ef,"RTI"            ; $b1 RTI
	.text	3,$f9,"RTS"            ; $b2 RTS
	.text	3,$d8,"SBC"            ; $b3 SBC
	.text	3,$db,"SEC"            ; $b4 SEC
	.text	3,$dc,"SED"            ; $b5 SED
	.text	3,$e1,"SEI"            ; $b6 SEI
	.text	3,$e8,"STA"            ; $b7 STA
	.text	3,$f7,"STP"            ; $b8 STP
	.text	3,$ff,"STX"            ; $b9 STX
	.text	3,$00,"STY"            ; $ba STY
	.text	3,$01,"STZ"            ; $bb STZ
	.text	3,$ed,"TAX"            ; $bc TAX
	.text	3,$ee,"TAY"            ; $bd TAY
	.text	3,$e8,"TRB"            ; $be TRB
	.text	3,$e9,"TSB"            ; $bf TSB
	.text	3,$ff,"TSX"            ; $c0 TSX
	.text	3,$ed,"TXA"            ; $c1 TXA
	.text	3,$ff,"TXS"            ; $c2 TXS
	.text	3,$ee,"TYA"            ; $c3 TYA
	.text	$FF
	.send code
