"""Build the SuperBASIC composite assembly file from `.asm`/`.inc` sources."""

import sys
from pathlib import Path


# sort includes by module name - e.g. without the first directory
def sortKey(k: Path):
    return ":".join(k.parts[1:])


# returns normalized path for 64tass includes
def include_path(path: Path) -> str:
    return "/".join(["."] + list(path.parts))


# returns 64tass include directive for `path`
def include_directive(path: Path) -> str:
    return '\t.include\t"{0}"\n'.format(include_path(path))


#
# Get a list of files involved
#
includeFiles: list[Path] = []  # include files in order
sourceFiles: list[Path] = []  # source files in order
moduleFiles: list[Path | str] = []
page2ModuleFiles: list[Path] = []

modulesIntegrated: dict[str, bool] = {}

root_dir = Path(".")
modules_dir = root_dir / "modules"
built_modules_dir = modules_dir / ".build"

modules = sys.argv[1:]
for spec in modules:
    module_name = spec[1:]
    if spec[0] == "+":
        if ":" in module_name:
            name, page = module_name.split(":", 1)
            assert int(page) == 2, "unrecognized module spec format `{spec}`"
            page2ModuleFiles.append(
                built_modules_dir / "{0}_p2.module.asm".format(name)
            )
        else:
            moduleFiles.append(built_modules_dir / "{0}.module.asm".format(module_name))

        modulesIntegrated[module_name] = True
    else:
        assert spec[0] == "-", f"unrecognized module spec format `{spec}`"
        moduleFiles.append("{0}Integrated = 0".format(module_name))

for path in root_dir.rglob("*"):  # scan the root dir
    # skip directories, files in the 'modules' dir (which has its own build procedure)
    # and files that start with underscore
    if path.is_dir() or path.parts[0] == "modules" or path.name.startswith("_"):
        continue

    if "module.interface" in path.parts:
        pos = path.parts.index("module.interface")
        interface = path.parts[pos:][1]  # check we are using this module
        if interface not in modulesIntegrated:
            continue

    if path.suffix == ".asm":
        sourceFiles.append(path)
    if path.suffix == ".inc":
        includeFiles.append(path)

includeFiles.sort(key=lambda path: sortKey(path))
sourceFiles.sort(key=lambda path: sortKey(path))

#
# Create the composite file to build the whole thing.
#
h = open("_basic.asm", "w")  # create the build file.
h.write(";\n;\tThis file is automatically generated\n;\n")  # output the build file


for path in includeFiles:
    h.write(include_directive(path))
h.write("\n\n")

# Place `fn.asm` last: `FunctionCall`` is safe at the $9FFF/$A000 page boundary
# because it is never called by paged modules.
lateFiles: list[Path] = []
for path in sourceFiles:
    if path.parent.name == "unary" and path.name == "fn.asm":
        lateFiles.append(path)
    else:
        h.write(include_directive(path))

for path in lateFiles:
    h.write(include_directive(path))
h.write("\n")

h.write("""
.section code
    ; issuing a warning instead of an error so one can examine output listing for details
    .cwarn * > $C000, "BROKEN BUILD: non-paged code overflows into kernel-reserved I/O space ($C000-$DFFF) by ", * - $C000," bytes"

StartModuleCode:
    .if PagingEnabled==1
        * = $A000
        .offs $2000
    .endif
.send code
""")
h.write("\n")

for spec in moduleFiles:
    if isinstance(spec, str):
        h.write("\t{0}\n".format(spec))
    else:
        h.write(include_directive(spec))


h.write("""
.section code
    ; issuing a warning instead of an error so one can examine output listing for details
    .cwarn * > $C000, "BROKEN BUILD: page 1 code overflows into kernel-reserved I/O space ($C000-$DFFF) by ", * - $C000," bytes"
.send code
""")

h.write("\n; --- Startup banner data in boot section ($6000-$7FFF) ---\n")
h.write(
    include_directive(modules_dir / "hardware" / "startup" / ".build" / "banner.dat")
)

if page2ModuleFiles:
    h.write("\n; --- Module page 2 (slot 3) ---\n")
    h.write("; page2 section at $4000 (below boot section at $6000)\n")
    h.write(
        "; .logical * + $2000 in each block maps labels to $6000+ runtime addresses\n"
    )
    h.write("\n; --- Error text in slot 3 module page ---\n")
    h.write(include_directive(root_dir / "common" / "generated" / "_errortext_p2.asm"))
    for path in page2ModuleFiles:
        h.write(include_directive(path))

    h.write("""
.section page2
.logical * + $2000
    ; issuing a warning instead of an error so one can examine output listing for details
    .cwarn * > $8000, "BROKEN BUILD: page 2 code overflows into SuperBASIC ROM space ($8000-$BFFF) by ", * - $8000," bytes"
.endlogical
.send page2
""")

# data overflow checks; keep these at the end!
h.write(
    include_directive(root_dir / "common" / "aa.system" / "_dataoverflowchecks.asm")
)

h.close()
